---
- name: Deploy nas
  hosts: docker_hosts
  become: true
  roles:
    - role: nmcli
    - role: setup_users
    - role: nvidia_drivers
      when: nvidia_drivers_install | default(false)
      tags:
        - nvidia_drivers

    - role: mount_nfs
    - role: languagetool
      when: "'languagetool' in deploy_docker_roles | default([])"
      tags:
        - docker
        - languagetool

    - role: unifi_controller
      when: "'unifi_controller' in deploy_docker_roles | default([])"
      tags:
        - docker
        - unifi_controller
    - role: nginx_ping
      when: "'nginx_ping' in deploy_docker_roles | default([])"
      tags:
        - docker
        - nginx_ping
    - role: gravity
      when: "'gravity' in deploy_docker_roles | default([])"
      tags:
        - docker
        - gravity
    - role: rommapp
      when: "'rommapp' in deploy_docker_roles | default([])"
      tags:
        - docker
        - rommapp
    - role: deploy_immich
      when: "'deploy_immich' in deploy_docker_roles | default([])"
      tags:
        - docker
        - immich
    - role: prometheus
      when: "'prometheus' in deploy_docker_roles | default([])"
      tags:
        - docker
        - prometheus
  tasks:
    - block:
      - name: Ensure deb deps
        ansible.builtin.apt:
          name:
            - python3-pip
            - python3-yaml
          state: present

      - name: Create docker stack
        community.docker.docker_compose_v2:
          project_name: "{{ item }}"
          definition: "{{ deploy_docker_service_definitions[item] }}"
        loop: "{{ deploy_docker_services | default([]) }}"
      tags:
        - docker
