
domain: int.ripplefcl.com
post_debian_clone_domain: "{{ domain }}"

setup_users_primary:
  - username: ripple
    sudo: true
    password: "{{ lookup('bws_cache', 'ripple_user_hashed_password').value }}"
    ssh_keys: ["{{ lookup('bws_cache', 'ripple_sshkey_pub').value }}"]

  - username: ansible
    sudo: true
    password: "{{ lookup('bws_cache', 'ansible_user_hashed_password').value }}"
    ssh_keys: ["{{ lookup('bws_cache', 'ripple_sshkey_pub').value }}"]

  - username: jens
    sudo: true
    ssh_keys: ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDdKEwJwQA8pazibRc+X6Z0QzuPDZz8goUU1OBF2TIzzS86MqEJ22Rwo/51mhKdpALIszOI3x/qX3QiyBtdQU3qbC+XxyxxINXLwziksd/g8JgaTg04N5f/wOw5U/N5WNV2N0kkMxaychJdO5B2NX52hY+Mr+GNNJJKvBxsBRx7jGq+0KsZdCO1vRKXTb7yHSdQlThQDKW2IpHhw/q39Y8BzO2rnV2Zz6KSC8MrCM6BH7MBAWJyLLMuFUJPY/jJa9G6jkCYY51iUGxp5RuMuJQTsnzFSzGfjh2MWgVePBPvIyy/65DPjpRLgMJ7VRKNHkW03YVYS6TJxltGp9PrcQ1e/ksncKzrDTcQX1xcl1vliwmstODFZQLgou+NHJUWL8cc0tsjUzSXgVEzQuSQmfdiB3yhqczZSsA2c9J+tGL7u3KhSaQ9IGQSlPVRnOEOhvhDxa4lGohEaQyW9iwXi1PffkBO4KPLiXCX04a+LfQeGLfm9/arh0xljmAmtEu2eUk="]
