---
- name: 'Make users'
  ansible.builtin.user:
    name: "{{ item.username }}"
    password: "{{ item.password | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"
    shell: /bin/bash
    create_home: true
  loop: "{{ setup_users_primary + setup_users_secondary }}"
  loop_control:
    label: "{{ item.username }}"

- name: 'Add users to suderos'
  community.general.sudoers:
    name: "{{ item.username }}-user"
    state: present
    user: "{{ item.username }}"
    commands: ALL
    runas: "{{ 'ALL:ALL' if item.runas | default(false) else omit }}"
  when: "item.sudo | default(false)"
  loop: "{{ setup_users_primary + setup_users_secondary }}"
  loop_control:
    label: "{{ item.username }}"


- name: Set users autherised ssh key
  ansible.builtin.include_tasks:
    file: setup_ssh_keys.yml
  loop: "{{ setup_users_primary + setup_users_secondary }}"
  loop_control:
    loop_var: "userdata"
    label: "{{ userdata.username }}"

- name: 'Add users to groups'
  ansible.builtin.user:
    name: "{{ item.username }}"
    groups: "{{ item.groups | default([]) }}"
    append: true
    state: present
  loop: "{{ setup_users_primary + setup_users_secondary }}"
  loop_control:
    label: "{{ item.username }}"
