setup_users_secondary:
  - username: plex
    password: "{{ lookup('bws_cache', 'ripple_user_hashed_password').value }}"
    uid: 1100

mount_nfs_shares:
  - path: /mnt/plex_media
    share: 10.2.3.1:/hdd-pool/hdd-nas/plex_media/nfs
    opts: rw,async,hard,intr,nofail,_netdev
  - path: /mnt/download_pool
    share: 10.2.3.2:/big-ssd-pool/ssd-nas/download/
    opts: rw,async,hard,intr,nofail,_netdev
  - path: /mnt/immich_data
    share: 10.2.3.1:/hdd-pool/hdd-nas/immich_data
    opts: rw,async,hard,nofail,_netdev

deploy_immich_image_dir: /mnt/immich_data/

nmcli_interfaces:
  - name: ens192
    method: manual
    gateway: "10.0.7.1"
    dns: "10.0.7.1"
    ip: 10.0.7.20/24

  - name: ens256
    method: manual
    ip: 10.2.3.10/24

deploy_docker_services:
  - plex_stack
  - wakapi

deploy_docker_roles:
  - deploy_immich

install_container_toolkit: true
nvidia_drivers_install: true
nvidia_cuda_pkg_version: "12.5.1-1"
