setup_users_secondary:
  - username: plex
    password: "{{ lookup('bws_cache', 'ripple_user_hashed_password').value }}"
    uid: 1100

zfs_pool_config:
  - name: "hdd-pool"
    options:
      compression: lz4
    vdevs:
      - type: raidz2
        devices:
          - ata-ST4000DM004-2CV104_ZTT4GY4Q
          - ata-TOSHIBA_MG03ACA400_25OAK0LLF
          - ata-TOSHIBA_MG03ACA400_25OAK0LMF
          - ata-TOSHIBA_MG03ACA400_25OAK0LNF
          - ata-TOSHIBA_MG03ACA400_25OAK0LOF
          - ata-TOSHIBA_MG03ACA400_25ODK58BF
          - ata-TOSHIBA_MG03ACA400_25OHK5ALF
          - ata-TOSHIBA_MG03ACA400_25OHK5AMF
          - ata-TOSHIBA_MG03ACA400_25PHK5CJF
          - ata-TOSHIBA_MG03ACA400_25PHK5CKF

zfs_fs_config:
  - pool: "hdd-pool/hdd-nas"
    options:
      compression: lz4
    mountpoint:
      owner: ripple
      group: ripple
      recurse: true
    datasets:
      - name: "vcenter"
        datasets:
          - name: "nfs"
            options:
              sync: always
            mountpoint:
              owner: root
              group: root
              recurse: true
      - name: "veeam"
        datasets:
          - name: "nfs"
            mountpoint:
              owner: root
              group: root
              recurse:
      - name: "plex_media"
        datasets:
          - name: "nfs"
            mountpoint:
              owner: plex
              group: plex
              recurse: true
      - name: "immich_data"
        mountpoint:
          owner: 1000
          group: 1000
      - name: "immich_data"
        mountpoint:
          owner: 1000
          group: 1000
      - name: "mac_data"
        mountpoint:
          owner: 501
          group: 20


zfs_performance_tuning:
  - param: zfs_arc_max
    value: "{{ (ansible_memtotal_mb | int * 1024 * 1024 * 0.9) | round | int }}"
  - param: zfs_arc_min
    value: "{{ (ansible_memtotal_mb | int * 1024 * 1024 * 0.8) | round | int }}"

zfs_pools_scrub_cron:
  - pool: ssd-pool
    minute: 0
    hour: 0
    day: "*"
    month: "*"
    weekday: sun


nfs_exports:
  - "/hdd-pool/hdd-nas/vcenter/nfs/ *(rw,sync,no_root_squash)"
  - "/hdd-pool/hdd-nas/veeam/nfs/ *(rw,sync,no_root_squash)"
  - "/hdd-pool/hdd-nas/plex_media/nfs/ *(rw)"
  - "/hdd-pool/hdd-nas/immich_data *(rw,no_root_squash)"
  - "/hdd-pool/hdd-nas/mac_data *(rw,no_root_squash)"


nmcli_interfaces:
  - name: ens192
    method: manual
    ip: 10.0.1.32/24
    gateway: 10.0.1.1
    dns: 1.1.1.1

  - name: ens256
    method: manual
    ip: 10.2.1.10/24

  - name: ens161
    method: manual
    ip: 10.2.3.1/24
