---
- name: Restart klipper
  ansible.builtin.systemd:
    name: klipper
    state: restarted
    daemon_reload: true
  become: true

- name: Restart moonraker
  ansible.builtin.systemd:
    name: moonraker
    state: restarted
    daemon_reload: true
  become: true

- name: Reboot
  ansible.builtin.reboot:
    msg: "Rebooting to apply changes"
    connect_timeout: 5
    reboot_timeout: 600
  become: true
